pages:
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  # - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - pages